all: dpcpp

dpcpp: B+TREE BACKPROP BFS CFD DWT2D GAUSSIAN HEARTWALL HOTSPOT HOTSPOT3D HUFFMAN LAVAMD LUD MYOCYTE NN NW PARTICLEFILTER PATHFINDER SRAD STREAMCLUSTER


B+TREE:
	cd b+tree; make

BACKPROP:
	cd backprop; make

BFS:
	cd bfs; make

CFD:
	cd cfd; make

DWT2D:
	cd dwt2d; make

GAUSSIAN:
	cd gaussian; make

HEARTWALL:
	cd heartwall; make

HOTSPOT:
	cd hotspot; make

HOTSPOT3D:
	cd hotspot3D; make

HUFFMAN:
	cd huffman; make

LAVAMD:
	cd lavaMD; make

LUD:
	cd lud; make

MYOCYTE:
	cd myocyte; make

NN:
	cd nn; make

NW:
	cd nw; make

PARTICLEFILTER:
	cd particlefilter; make

PATHFINDER:
	cd pathfinder; make

SRAD:
	cd srad; make

STREAMCLUSTER:
	cd streamcluster; make



clean: B+TREE_clean BACKPROP_clean BFS_clean CFD_clean DWT2D_clean GAUSSIAN_clean HEARTWALL_clean HOTSPOT_clean HOTSPOT3D_clean HUFFMAN_clean LAVAMD_clean LUD_clean MYOCYTE_clean NN_clean NW_clean PARTICLEFILTER_clean PATHFINDER_clean SRAD_clean STREAMCLUSTER_clean

B+TREE_clean:

	cd b+tree; make clean

BACKPROP_clean: 

	cd backprop; make clean

BFS_clean:

	cd bfs; make clean

CFD_clean:

	cd cfd; make clean

DWT2D_clean:

	cd dwt2d; make clean

GAUSSIAN_clean:

	cd gaussian; make clean

HEARTWALL_clean:

	cd heartwall; make clean

HOTSPOT_clean:

	cd hotspot; make clean

HOTSPOT3D_clean:

	cd hotspot3D; make clean

HUFFMAN_clean:

	cd huffman; make clean

LAVAMD_clean:

	cd lavaMD; make clean

LUD_clean:

	cd lud; make clean

MYOCYTE_clean:

	cd myocyte; make clean

NN_clean:

	cd nn; make clean

NW_clean:

	cd nw; make clean

PARTICLEFILTER_clean:

	cd particlefilter; make clean

PATHFINDER_clean:

	cd pathfinder; make clean

SRAD_clean:

	cd srad; make clean

STREAMCLUSTER_clean:

	cd streamcluster; make clean
